import styles from '../styles/Home.module.css'
import Head from 'next/head'
import Link from 'next/link';

export default function About() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      {/* Create navbar */}
      <nav className={styles.navbar}>
        <div className={styles.navbarLinks}>
          <Link href="/">Home</Link>
          <Link href="/record">Record</Link>
          <Link href="/plan">Training Plans</Link>
          <Link href="/map">Mapping</Link>
        </div>
      </nav>
    </div>
  )
}